name: Environment Sync Check

on:
  pull_request:
    paths:
      - '.github/**'
      - 'docker-compose.ci.yml'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Makefile'

jobs:
  verify:
    name: Verify Native/Docker Sync
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get native environment
        uses: ./.github/actions/setup
      - run: |
          uv pip freeze | sort > /tmp/native-deps.txt
          python --version > /tmp/native-version.txt

      - name: Get Docker environment
        run: |
          docker compose -f docker-compose.ci.yml run ci \
            sh -c "pip freeze | sort" > /tmp/docker-deps.txt
          docker compose -f docker-compose.ci.yml run ci \
            python --version > /tmp/docker-version.txt

      - name: Compare environments
        run: |
          echo "=== Python Version Diff ==="
          diff /tmp/native-version.txt /tmp/docker-version.txt || true
          echo "=== Dependencies Diff ==="
          diff /tmp/native-deps.txt /tmp/docker-deps.txt || true

          # Fail if there are differences
          if ! diff -q /tmp/native-version.txt /tmp/docker-version.txt; then
            echo "❌ Python versions differ!"
            exit 1
          fi

          if ! diff -q /tmp/native-deps.txt /tmp/docker-deps.txt; then
            echo "⚠️ Dependencies differ (may be OK for different platforms)"
          fi

          echo "✅ Environments are in sync!"